# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.4
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ab:57:d3:0c:18:f5:bf:b6:e8:a9:b6:0e:9a:bf:d3:0f"
            - "b8:43:7f:7d:bf:7f:1c:6c:80:3d:00:8f:47:8a:d7:02"
      - checkout
      - run: make test
